package votingsystem;

import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author jakee
 */
public class VotingScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VotingScreen.class.getName());

    /**
     * Creates new form VotingScreen
     */
    public VotingScreen() {
        
        initComponents();
        this.userId = 0;
        
    }
    
    public VotingScreen(int userId,String username) {
    initComponents();
    //Yung user_Id ay manggagaling sa Login Frame base kung anong account ang ilologin ng voter
    this.userId = userId;
    setTitle("Voting - " + username);
    loadCandidates();
    
    
    if (hasAlreadyVoted()) {
        javax.swing.JOptionPane.showMessageDialog(this, "You already voted.\n\nYour votes:\n" + getMyVotesSummary());
        lockVotingUI();
    }

}
    
private final int userId;

// position -> ButtonGroup (so only 1 selected per position)
private final java.util.Map<String, javax.swing.ButtonGroup> groupByPosition = new java.util.LinkedHashMap<>();

    
private void loadCandidates() {

    candidatesPanel.removeAll();
    candidatesPanel.setLayout(new javax.swing.BoxLayout(candidatesPanel, javax.swing.BoxLayout.Y_AXIS));
    groupByPosition.clear();

    String sql = """
        SELECT id, name, position
        FROM candidates
        ORDER BY position_order, name
    """;

    String currentPosition = null;
    javax.swing.JPanel currentRow = null;

    try (java.sql.Connection conn = DB.connect();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            int candidateId = rs.getInt("id");
            String name = rs.getString("name");
            String position = rs.getString("position");

            // new position section
            if (currentPosition == null || !currentPosition.equals(position)) {
                currentPosition = position;

                javax.swing.JLabel header = new javax.swing.JLabel(position);
                header.setFont(header.getFont().deriveFont(java.awt.Font.BOLD, 14f));
                header.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 0, 6, 0));
                header.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

                // wrapper that forces left placement
                javax.swing.JPanel headerWrap = new javax.swing.JPanel(new java.awt.BorderLayout());
                headerWrap.setOpaque(false);
                headerWrap.add(header, java.awt.BorderLayout.WEST);

                candidatesPanel.add(headerWrap);


                currentRow = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT,10,5));
                candidatesPanel.add(currentRow);

                groupByPosition.put(position, new javax.swing.ButtonGroup());
            }

            // candidate card
            javax.swing.JPanel card = new javax.swing.JPanel(new java.awt.BorderLayout(8, 0));
            card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY),
                    javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)
            ));

            javax.swing.JLabel nameLabel = new javax.swing.JLabel(name);

            javax.swing.JRadioButton radio = new javax.swing.JRadioButton();
            radio.setActionCommand(String.valueOf(candidateId)); // IMPORTANT
            groupByPosition.get(position).add(radio);

            card.add(nameLabel, java.awt.BorderLayout.CENTER);
            card.add(radio, java.awt.BorderLayout.EAST);

            currentRow.add(card);
        }

        candidatesPanel.revalidate();
        candidatesPanel.repaint();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Load error: " + e.getMessage());
    }
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        candidatesPanel = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        candidatesPanel.setBackground(new java.awt.Color(204, 204, 204));
        candidatesPanel.setLayout(new javax.swing.BoxLayout(candidatesPanel, javax.swing.BoxLayout.Y_AXIS));

        btnSubmit.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        btnSubmit.setText("Send Vote");
        btnSubmit.setPreferredSize(new java.awt.Dimension(100, 120));
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabel2.setText("\"Your Vote. Your Voice.\"");

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SSG Candidate Officers");

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(candidatesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(candidatesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        setSize(new java.awt.Dimension(876, 859));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // 1) Validate: must choose 1 candidate per position
        for (var entry : groupByPosition.entrySet()) {
            String position = entry.getKey();
            javax.swing.ButtonGroup group = entry.getValue();

            if (group.getSelection() == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a candidate for: " + position);
                return;
            }
        }

        // 2) Confirm submit
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Submit your votes now? You may not be able to change after submitting.",
            "Confirm Submit",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        String insert = "INSERT INTO votes(user_id, position, candidate_id) VALUES(?,?,?)";

        // 3) Save in one transaction
        try (java.sql.Connection conn = DB.connect();
            java.sql.PreparedStatement ps = conn.prepareStatement(insert)) {

            conn.setAutoCommit(false);

            for (var entry : groupByPosition.entrySet()) {
                String position = entry.getKey();
                javax.swing.ButtonGroup group = entry.getValue();

                int candidateId = Integer.parseInt(group.getSelection().getActionCommand());

                ps.setInt(1, userId);
                ps.setString(2, position);
                ps.setInt(3, candidateId);
                ps.addBatch();
            }

            ps.executeBatch();
            conn.commit();

            javax.swing.JOptionPane.showMessageDialog(this, "Votes submitted successfully!");

            // 4) Lock UI after submit
        lockVotingUI();

        } catch (java.sql.SQLException e) {
            // UNIQUE(user_id, position) triggers if user already voted
            String msg = (e.getMessage() != null && e.getMessage().toLowerCase().contains("unique"))
            ? "You already voted. Submission blocked."
            : "Database error: " + e.getMessage();
            javax.swing.JOptionPane.showMessageDialog(this, msg);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to logout?",
        "Confirm Logout",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        // Open Login Screen
        LoginFrame login = new LoginFrame();
        login.setVisible(true);

        // Close current Voting Screen
        this.dispose();
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void lockVotingUI() {
        // Disable all radio buttons inside candidatesPanel
        for (java.awt.Component comp : candidatesPanel.getComponents()) {
            disableRadiosRecursive(comp);
        }
        btnSubmit.setEnabled(false);
}

    private void disableRadiosRecursive(java.awt.Component comp) {
        if (comp instanceof javax.swing.JRadioButton rb) {
            rb.setEnabled(false);
        } else if (comp instanceof java.awt.Container container) {
            for (java.awt.Component child : container.getComponents()) {
                disableRadiosRecursive(child);
            }
        }
}
    
    private boolean hasAlreadyVoted() {
    String sql = "SELECT COUNT(*) AS total FROM votes WHERE user_id = ?";

    try (java.sql.Connection conn = DB.connect();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setInt(1, userId);

        try (java.sql.ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                return rs.getInt("total") > 0;
            }
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "DB error: " + e.getMessage());
    }

    return false;
}
    
    private String getMyVotesSummary() {
    String sql = """
        SELECT v.position, c.name
        FROM votes v
        JOIN candidates c ON v.candidate_id = c.id
        WHERE v.user_id = ?
        ORDER BY c.position_order
    """;


    StringBuilder sb = new StringBuilder();

    try (java.sql.Connection conn = DB.connect();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setInt(1, userId);

        try (java.sql.ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                sb.append(rs.getString("position"))
                  .append(": ")
                  .append(rs.getString("name"))
                  .append("\n");
            }
        }

    } catch (Exception e) {
        return "Error reading votes: " + e.getMessage();
    }

    return sb.length() == 0 ? "No votes found." : sb.toString();
}



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VotingScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel candidatesPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
